### ISSUE TITLE
Inaccurate State change with above target

### ISSUE THREAD

**Issue by jessicatrnh** [acq4/acq4#158]
After hitting above target, State in multipatch does not change to In Bath--stays in out mode

**Comment by outofculture** [comment]
This bug should be fixed in `outofculture:158-bathing_from_above`, the linked PR.

**Comment by jessicatrnh** [comment]
This specific state issue is now fixed (Thanks!) but a separate and related issue: state inaccurately changes to Whole Cell after fully retracted from tissue (after Reseal function in MIES module is completed).

**Comment by outofculture** [comment]
hrm. I'm having trouble tracing through to find where in the code this happens. @campagnola do you have a suggestion? 'whole cell' gets only reference a few times, but notably, the `_transition_to_seal` method that Reseal attempts to use isn't actually defined in its class hierarchy, so I expect reseal to blow up instead of successfully sealing. we can pair on this on Monday.

otherwise, @jessicatrnh, do you have a log file from a time where this happened? I can maybe track it down from that.

**Comment by outofculture** [comment]
oh wait! this is on the old code, where 'whole cell' was the default reseal fallback. yeah, okay, #157 is going to take care of this, I think.
