### ISSUE TITLE
In cell attached mode, monitor resistance for break-in

### ISSUE THREAD

**Issue by campagnola** [acq4/acq4#181]

**Comment by outofculture** [comment]
We cannot rely on just resistance, as a failed seal will also show a drop in resistance. This is therefore a need for a better capacitance calculation so that both can be used in concert to determine when a spontaneous break-in has occurred. Look at the neuroanalysis package for cell models that can provide testing of our analysis code.

**Comment by jessicatrnh** [comment]
Recent examples of cells that make it to initial gigaohm seal but the state moves quickly and inaccurately through 'cell-attached' and to 'whole-cell' (before cell is broken into and maintains SR>1Gohm):

autopatch_test\2024.06.11_000\slice_000\cell_002
autopatch_test\2024.06.11_000\slice_001\cell_002
autopatch_test\2024.06.13_000\slice_000\cell_000
autopatch_test\2024.06.13_000\slice_000\cell_001
autopatch_test\2024.06.13_000\slice_000\cell_005
autopatch_test\2024.06.13_000\slice_001\cell_000

**Comment by jessicatrnh** [comment]
@outofculture fixed! We added parameters to the 'cell attached' state in the default config. The state changes from seal to cell-attached for a successful gigaseal, and then to whole cell once the cell is broken into successfully. 

Here is what was added:

- capacitanceThreshold: 50*pF
-                 resistanceThreshold: 500*MOhm
-                 holdingCurrentThreshold: -1*nA
-                 spontaneousBreakInState: 'break in'
-                 spontaneousDetachmentState: 'fouled'
