### ISSUE TITLE
initial pressure not set correctly in seal mode

### ISSUE THREAD

**Issue by outofculture** [acq4/acq4#208]
Observed in mid-experiment; setting startingPressure to -1kPa, it seemed like the pressure started at 0. Didn't have time to investigate further.

**Comment by jessicatrnh** [comment]
The comment above applied when the approach experienced no fouls...however when there is a foul the -1kPa does not seem to apply. I'll test this few more times and give updates on consistency.

**Comment by jessicatrnh** [comment]
For some reason, -70mV is no longer being applied when SSR>100MOhm.

**Comment by jessicatrnh** [comment]
@outofculture Better. -1kPa is now being applied for a longer before it times out and switches to atmospheric mode. -70mV still not being applied when SS resistance >100MOhm.

This error also occurs when the seal feature is applied


![Image](https://github.com/acq4/acq4/assets/43593980/4d84a114-9e4c-4466-aa43-843612f93407)

**Comment by jessicatrnh** [comment]
Extra observations from today:
Seal feature: IF a gigaseal is reached during the continuous application of -1kPa, then the state switched to cell attached, as it should. 

Otherwise, if gigaseal is not obtained in this period, then mode switching is enabled to switch between atmospheric and regulator (@ -1kPa) mode (5 iterations) and then feature times out. The operator must take over to obtain a gigaseal and subsequently select cell attached state or reapply the Seal function. 

In both situations, operator still needs to adjust holding V.

**Comment by jessicatrnh** [comment]
still seeing issues where -1kPa not being applied continuously when seal mode is enabled.
